### ISSUE TITLE
click button inside rbd don't blur element outside.

### ISSUE THREAD

**Issue by TotooriaHyperion** [atlassian/react-beautiful-dnd#1645]
### Expected behavior
click button inside rbd should cause outer elements to blur.

### Actual behavior
click button inside rbd makes any element's blur event disabled.

### Steps to reproduce
simple as said in behavior

**Comment by alexreardon** [comment]
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by alexreardon** [comment]
I think this issue was fixed in 12.x. Please upgrade and take another look

**Comment by TotooriaHyperion** [comment]
> I think this issue was fixed in 12.x. Please upgrade and take another look

https://codesandbox.io/s/vertical-list-nnlhb

reproduce, seems still the same on v12.

**Comment by alexreardon** [comment]
I can explain *why* this is happening, but i'm not sure if we can do much about it at this stage

- in our [mouse sensor](/docs/sensors/mouse.md) we *need* to call `event.preventDefault()` on mousedown events that we *think* could be starting a drag. See [how we use dom events](/docs/guides/how-we-use-dom-events.md). This is to prevent the drag handle from getting focus (which is what would happen because it has a tabIndex)

This is unfortunate as it means that clicking on a drag handle will not cause it to gain focus or for the other item to lose focus.

I think you hit on the right solution: manually cause the element to get focus in your on click (if you want to). 

```
function onClick(event) {
 // we used the event for dragging
 if(event.defaultPrevented) {
    return;
 }

 event.currentTarget.focus();
}
```

Perhaps we should add this be default?

**Comment by alexreardon** [comment]
Perhaps we could always our own click handler after we prevent default on a mousedown to ensure focus is correctly given to the element if a click does occur 🤔

**Comment by TotooriaHyperion** [comment]
I think should also allow inner element to get focused if it's clicked, if not focusable, focus the drag handle.
Also the focus should fire before the user's own onClick event because the native focus/blur fire before click(mousedown -> blur/focus -> mouseup -> click), so I use onClickCapture.

```javascript
    function onClickCapture(event) {
      if (e.defaultPrevented) {
        return;
      }
      if (e.currentTarget !== e.target && e.target.tabIndex >= 0) {
        e.target.focus();
      } else {
        e.currentTarget.focus();
      }
    }
```
https://codesandbox.io/s/clever-zhukovsky-rxh22

feels much more intuitive.

**Comment by alexreardon** [comment]
It would be worth thinking through what the behaviour should be for sure

**Comment by nohimys** [comment]
Was there any update about this issue in any of the later releases ?

**Comment by linkfang** [comment]
Having same issue when I tried to add `:focus` style for a draggable item. 

We need this `:focus` style, because in our case, each item is clickable and draggable. We will show more detail info on the item that is clicked on. And we want to highlight it to indicate the user which one they are looking at.

I think it's better to at least explain this issue in the doc with potential solutions (like in FAQ section?), so that users don't need to dig into issue list trying to find if there is an existing issue and how to solve it.

Hope this could be fixed or at least added into docs. Thanks!

**Comment by shamseer-ahammed** [comment]
+1
