### ISSUE TITLE
Flickering on single props update

### ISSUE THREAD

**Issue by kolyasya** [atlassian/react-beautiful-dnd#2305]
Hello, I'm implementing a simple list with draggable items.

It works like usual: 
1. You drag an item
2. It should stay in new place
3. Client calls a server for data update
4. On success client reactively gets an updated data with new order
5. Order of items in UI still stays the same for a user

But in my case when new data arrives a have a millisecond flickering with initial order of items.

I've checked that I have only a single props update when drag is finished, meaning I don't affect an order of items somehow by my code.

Any ideas what do I need to check?

Here is a short demo:

https://user-images.githubusercontent.com/3371143/132088867-db938a1a-3986-4514-b4bb-aaba00f94dfc.mov

I'm using the package with my Meteor app, so it is tricky to put the code demo in.

So the main part of the component looks like and reactively gets a sortedAccounts list after update:

```
return (
    <DragDropContext onDragEnd={onDragEnd}>
      <Droppable droppableId="droppable">
        {provided => (
          <Box
            className="accounts-list"
            {...provided.droppableProps}
            ref={provided.innerRef}
            py="2"
          >
            {sortedAccounts?.map((account, index) => (
              <AccountRow
                key={account?._id}
                index={index}
                account={account}
                onAccountRowClick={onAccountRowClick}
                active={(accountsIds || []).includes(account?._id)}
              />
            ))}
            {provided?.placeholder}
          </Box>
        )}
      </Droppable>
    </DragDropContext>
  );
```

**Comment by R-Bower** [comment]
@kolyasya this is fixed in the forked/updated version of this library:
https://github.com/hello-pangea/dnd

**Comment by rbista** [comment]
> @kolyasya this is fixed in the forked/updated version of this library: https://github.com/hello-pangea/dnd

I tried this but still facing similar issue as shown in above video.
